### ISSUE TITLE
WAR-file

### ISSUE THREAD

**Issue by dawalt** [mpetris/catma#126]
Hi,

I have problems creating a build one my local machine.

I get these Ivy-Errors:
```

	::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: de.catma#catma-core;latest.integration: not found

		::::::::::::::::::::::::::::::::::::::::::::::

:: problems summary ::
:::: WARNINGS
		module not found: de.catma#catma-core;latest.integration

```

Could someone provide a deployable WAR-File?

Best Regards
David

**Comment by mpetris** [comment]
Hi, we are using Eclipse with Apache Ivy 2.4.0 and Apache IvyDE 2.2.0 plugins to resolve the dependencies and to build CATMA. You need to configure IvyDE to "Resolve dependencies in workspace" via Eclipse Preferences->Ivy->Classpath. This should solve the problem. If you need a deployable WAR please contact me directly by [email](http://catma.de/contact/).
